#!/bin/bash

### The single argument to this script is the date of the 1st day of
### the sesshin, which is also the name of the directory in
### sesshin-greeter/sesshins containing the docs. For example
### ~/rzc/sesshin-greeter/sesshins/2018-01-06.
###
### The `--main' option invokes the procedure called "main" with the
### command line arguments.

(cd /tmp
 racket --require ~/rzc/sesshin-greeter/etc/greet.rkt --main $*)
cp /tmp/$1-{sessh,slips}.pdf .
