#!/bin/bash

### The single argument to this script is the date of the 1st day of
### the sesshin, which is also the name of the directory in
### sesshin-greeter containing the docs. For example
### ~/rzc/sesshin-greeter/2018-01-06.
###
### The `--main' option invokes the procedure called "main" with the
### command line arguments.

racket --require ~/rzc/sesshin-greeter/etc/greet.rkt --main $*
